{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./env.nix
    ./home-manager.nix
    ./hyprland.nix
    ./kernel.nix
    ./mime.nix
    ./net.nix
    ./nh.nix
    ./nix.nix
    ./timezone.nix
    ./user.nix
    ./zram.nix
    ./steam.nix
    ./gamemode.nix
    ./waydroid.nix
    ./keyring.nix
  ];
}
